name: galvany_explorations
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  flutter_roomplan: ^1.0.7
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  open_filex: ^4.3.4
  apple_maps_flutter: ^1.4.0
  geolocator: ^11.1.0
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
